import React, { useState } from 'react';
import ChapterLayout from '../components/ChapterLayout';
import { Book, Database, Lock, UserCircle, ShieldAlert, Fingerprint, Calendar, Activity, Hash, FileText, Search, RefreshCw } from 'lucide-react';

const Chapter76 = () => {
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedPrivacy, setSelectedPrivacy] = useState('All');

  const dictionaryData = [
    {
      entity: 'Patient',
      field: 'national_id',
      type: 'VARCHAR(64+) / token reference',
      privacy: 'PII',
      desc: 'Use a keyed token/reference; never store a reversible or truncated national ID hash.',
      icon: Fingerprint,
      color: 'teal'
    },
    {
      entity: 'Patient',
      field: 'birth_date',
      type: 'DATE',
      privacy: 'PHI',
      desc: 'Required for precise medicine dosing.',
      icon: Calendar,
      color: 'orange'
    },
    {
      entity: 'Patient',
      field: 'blood_group',
      type: 'ENUM',
      privacy: 'PHI',
      desc: 'Blood type (A+, O-, etc).',
      icon: Activity,
      color: 'purple'
    },
    {
      entity: 'Encounter',
      field: 'encounter_id',
      type: 'UUID',
      privacy: 'PII/PHI context',
      desc: 'Unique session / visit ID.',
      icon: Hash,
      color: 'blue'
    },
    {
      entity: 'Encounter',
      field: 'chief_complaint',
      type: 'TEXT',
      privacy: 'PHI',
      desc: 'Raw text input from the patient.',
      icon: FileText,
      color: 'orange'
    },
    {
      entity: 'Encounter',
      field: 'triage_level',
      type: 'INTEGER',
      privacy: 'PHI',
      desc: 'Priority generated by AI (1-5).',
      icon: ShieldAlert,
      color: 'red'
    },
    {
      entity: 'MedicalRecord',
      field: 'diagnoses',
      type: 'FHIR Condition[] / coded reference',
      privacy: 'PHI',
      desc: 'List of ICD-10 codes for confirmed patient diagnoses.',
      icon: FileText,
      color: 'orange'
    },
    {
      entity: 'Prescription',
      field: 'prescription_id',
      type: 'UUID',
      privacy: 'PII/PHI context',
      desc: 'Unique electronic prescription identifier.',
      icon: Hash,
      color: 'blue'
    },
    {
      entity: 'Prescription',
      field: 'medications',
      type: 'FHIR MedicationRequest[] / coded reference',
      privacy: 'PHI',
      desc: 'List of drug codes, dosages, and usage frequencies.',
      icon: Activity,
      color: 'orange'
    }
  ];

  const filteredData = dictionaryData.filter(item => {
    const matchesSearch = 
      item.entity.toLowerCase().includes(searchQuery.toLowerCase()) ||
      item.field.toLowerCase().includes(searchQuery.toLowerCase()) ||
      item.type.toLowerCase().includes(searchQuery.toLowerCase()) ||
      item.desc.toLowerCase().includes(searchQuery.toLowerCase());
    
    const matchesPrivacy = selectedPrivacy === 'All' || item.privacy === selectedPrivacy;

    return matchesSearch && matchesPrivacy;
  });

  return (
    <ChapterLayout 
      title="فرهنگ داده (Data Dictionary)"
      chapterNumber={Number(76)}
    >
      <div className="prose prose-lg max-w-none text-right" dir="rtl">
        
      <section className="mb-12 animate-fade-in">
        <div className="flex items-center gap-3 mb-8 border-b border-[var(--border-color)] pb-4">
          <div className="p-3 rounded-2xl bg-[rgba(20,184,166,0.1)] border border-[rgba(20,184,166,0.2)]">
            <Book className="w-8 h-8 text-[var(--accent-teal)]" />
          </div>
          <div>
            <h2 className="text-3xl font-black m-0 bg-clip-text text-transparent bg-gradient-to-r from-[var(--accent-teal)] to-[var(--accent-blue)]">
              فرهنگ داده اجرایی
            </h2>
            <p className="text-sm premium-text-secondary mt-1 mb-0 font-medium tracking-wide">(Data Dictionary)</p>
          </div>
        </div>
        
        <div className="glass-panel p-6 mb-8 relative overflow-hidden group">
          <div className="absolute top-0 left-0 w-32 h-32 bg-[var(--accent-teal)] opacity-5 rounded-full blur-3xl group-hover:opacity-10 transition-opacity"></div>
          <p className="premium-text-secondary text-sm leading-relaxed relative z-10 m-0 flex items-start gap-2">
            <Database className="w-5 h-5 text-[var(--accent-teal)] shrink-0 mt-0.5" />
            <span>
              این جدول فقط نمونه اولیه است و هنوز Data Dictionary اجرایی نیست. نسخه کامل باید برای هر عنصر، تعریف بالینی، منبع، مالک، nullability، اعتبارسنجی، terminology binding، provenance، retention، lineage و نگاشت FHIR را ثبت کند.
            </span>
          </p>
        </div>

        {/* Filters Panel */}
        <div className="glass-panel p-6 mb-6 flex flex-col md:flex-row gap-4 items-center justify-between">
          <div className="relative w-full md:w-72">
            <Search className="absolute right-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
            <input 
              type="text"
              placeholder="جستجو در فیلدها، نوع داده یا توضیحات..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-4 pr-10 py-2.5 rounded-xl border border-[var(--border-color)] bg-[var(--bg-primary)] text-sm text-[var(--text-primary)] focus:outline-none focus:border-[var(--accent-teal)] transition-colors text-right"
              dir="rtl"
            />
          </div>

          <div className="flex flex-wrap gap-2 w-full md:w-auto justify-end">
            <span className="text-xs premium-text-secondary self-center ml-2 font-medium">فیلتر محرمانگی:</span>
            {['All', 'PII', 'PHI', 'N/A'].map(privacy => (
              <button
                key={privacy}
                onClick={() => setSelectedPrivacy(privacy)}
                className={`px-3.5 py-1.5 rounded-xl text-xs font-semibold transition-all duration-200 ${
                  selectedPrivacy === privacy 
                    ? 'bg-[var(--accent-teal)] text-white shadow-md' 
                    : 'bg-[var(--bg-primary)] border border-[var(--border-color)] premium-text-secondary hover:border-gray-500'
                }`}
              >
                {privacy === 'All' ? 'همه سطوح' : privacy}
              </button>
            ))}

            {(searchQuery || selectedPrivacy !== 'All') && (
              <button 
                onClick={() => { setSearchQuery(''); setSelectedPrivacy('All'); }}
                className="p-2 rounded-xl bg-red-500/10 border border-red-500/20 text-red-500 hover:bg-red-500/20 transition-colors flex items-center gap-1 text-xs"
                title="بازنشانی فیلترها"
              >
                <RefreshCw className="w-3.5 h-3.5" />
                <span>حذف فیلتر</span>
              </button>
            )}
          </div>
        </div>

        {/* Stateful Data Dictionary Table */}
        <div className="glass-panel p-1 border border-[var(--border-color)] rounded-2xl shadow-lg">
          <div className="premium-table-container rounded-xl overflow-hidden bg-[var(--bg-primary)]">
            {filteredData.length > 0 ? (
              <table className="premium-table font-mono w-full" dir="ltr">
                <thead>
                  <tr className="bg-gradient-to-r from-transparent to-[rgba(14,165,233,0.05)]">
                    <th className="text-left py-4 pl-6"><div className="flex items-center gap-2"><UserCircle className="w-4 h-4 text-[var(--accent-blue)]"/> Entity</div></th>
                    <th className="text-left"><div className="flex items-center gap-2"><FileText className="w-4 h-4 text-gray-500"/> Field Name</div></th>
                    <th className="text-left"><div className="flex items-center gap-2"><Hash className="w-4 h-4 text-gray-500"/> Data Type</div></th>
                    <th className="text-center"><div className="flex items-center justify-center gap-2"><Lock className="w-4 h-4 text-red-500"/> Privacy</div></th>
                    <th className="text-left pr-6"><div className="flex items-center gap-2"><Activity className="w-4 h-4 text-gray-500"/> Description</div></th>
                  </tr>
                </thead>
                <tbody className="text-sm text-left">
                  {filteredData.map((row, idx) => {
                    const RowIcon = row.icon;
                    return (
                      <tr 
                        key={idx} 
                        className={`hover:bg-[rgba(14,165,233,0.02)] transition-colors group ${
                          idx === filteredData.length - 1 ? 'border-b-0' : ''
                        }`}
                      >
                        <td className="font-bold text-[var(--accent-blue)] pl-6">
                          <span className="bg-[var(--bg-secondary)] px-2.5 py-1 rounded-lg border border-[var(--border-color)] text-xs font-semibold">
                            {row.entity}
                          </span>
                        </td>
                        <td className="font-semibold premium-text-primary">
                          <div className="flex items-center gap-1.5">
                            <RowIcon className={`w-4 h-4 text-gray-400 group-hover:text-[var(--accent-${row.color})] transition-colors`} />
                            {row.field}
                          </div>
                        </td>
                        <td className="text-xs">
                          <span className="premium-text-secondary bg-[var(--bg-secondary)] px-2 py-1 rounded border border-[var(--border-color)]">
                            {row.type}
                          </span>
                        </td>
                        <td className="text-center">
                          <span className={`badge shadow-sm ${
                            row.privacy === 'PII' ? 'badge-red' : row.privacy === 'PHI' ? 'badge-orange' : 'badge-gray opacity-80'
                          }`}>
                            {row.privacy}
                          </span>
                        </td>
                        <td className="premium-text-secondary pr-6 leading-relaxed">{row.desc}</td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            ) : (
              <div className="p-12 text-center">
                <Search className="w-12 h-12 text-gray-400 mx-auto mb-4 opacity-50" />
                <h4 className="font-bold text-lg m-0 premium-text-primary">هیچ فیلدی یافت نشد</h4>
                <p className="text-sm premium-text-secondary mt-2 mb-0">موردی متناسب با فیلترها و عبارت جستجوی شما پیدا نشد.</p>
              </div>
            )}
          </div>
        </div>
      </section>
        
      </div>
    </ChapterLayout>
  );
};

export default Chapter76;
