import React from 'react';
import ChapterLayout from '../components/ChapterLayout';

const Chapter76 = () => {
  return (
    <ChapterLayout 
      title="فرهنگ داده (Data Dictionary)"
      chapterNumber={Number(76)}
    >
      <div className="prose prose-lg max-w-none prose-headings:text-gray-800 prose-p:text-gray-600 text-right" dir="rtl">
        
      <section className="mb-12 animate-fade-in">
        <h2 className="text-2xl font-bold mb-6 premium-text-accent border-b border-[var(--border-color)] pb-2">فرهنگ داده اجرایی (Data Dictionary)</h2>
        <div className="premium-table-container">
          <table className="premium-table font-mono" dir="ltr">
            <thead>
              <tr>
                <th className="text-left">Entity</th>
                <th className="text-left">Field Name</th>
                <th className="text-left">Data Type</th>
                <th className="text-center">Privacy</th>
                <th className="text-left">Description</th>
              </tr>
            </thead>
            <tbody className="text-sm text-left">
              <tr>
                <td className="font-bold text-[var(--accent-blue)]" rowSpan="3">Patient</td>
                <td className="font-semibold premium-text-primary">national_id</td>
                <td className="text-xs premium-text-secondary">VARCHAR(10)</td>
                <td className="text-center"><span className="badge badge-red">PII</span></td>
                <td className="premium-text-secondary">Hashed ID of the user.</td>
              </tr>
              <tr>
                <td className="font-semibold premium-text-primary">birth_date</td>
                <td className="text-xs premium-text-secondary">DATE</td>
                <td className="text-center"><span className="badge badge-orange">PHI</span></td>
                <td className="premium-text-secondary">Required for precise medicine dosing.</td>
              </tr>
              <tr>
                <td className="font-semibold premium-text-primary">blood_group</td>
                <td className="text-xs premium-text-secondary">ENUM</td>
                <td className="text-center"><span className="badge badge-gray">N/A</span></td>
                <td className="premium-text-secondary">Blood type (A+, O-, etc).</td>
              </tr>
              <tr className="bg-[rgba(14,165,233,0.05)] border-t border-[var(--border-color)]">
                <td className="font-bold text-[var(--accent-teal)]" rowSpan="3">Encounter</td>
                <td className="font-semibold premium-text-primary">encounter_id</td>
                <td className="text-xs premium-text-secondary">UUID</td>
                <td className="text-center"><span className="badge badge-gray">N/A</span></td>
                <td className="premium-text-secondary">Unique session / visit ID.</td>
              </tr>
              <tr className="bg-[rgba(14,165,233,0.05)]">
                <td className="font-semibold premium-text-primary">chief_complaint</td>
                <td className="text-xs premium-text-secondary">TEXT</td>
                <td className="text-center"><span className="badge badge-orange">PHI</span></td>
                <td className="premium-text-secondary">Raw text input from the patient.</td>
              </tr>
              <tr className="bg-[rgba(14,165,233,0.05)]">
                <td className="font-semibold premium-text-primary">triage_level</td>
                <td className="text-xs premium-text-secondary">INTEGER</td>
                <td className="text-center"><span className="badge badge-gray">N/A</span></td>
                <td className="premium-text-secondary">Priority generated by AI (1-5).</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>
        
      </div>
    </ChapterLayout>
  );
};

export default Chapter76;
