import { 
  Home, LayoutDashboard, Target, Building2, TrendingUp, Cpu, Workflow, 
  Server, Brain, Database, BrainCircuit, DollarSign, Store, Globe, 
  PieChart, Users, Settings, BookOpen, Globe2, Shield, Scale, Link, 
  Smartphone, ShieldAlert, Activity, Download, Search, FileText, 
  FileSearch, HelpCircle, Network, UserCheck, Stethoscope, Briefcase, 
  Key, CheckCircle, ClipboardList, BookMarked, Share2 
} from 'lucide-react';

export const chapters = [
  { id: '0', path: '/', title: 'داشبورد اصلی', subtitle: 'Home', icon: Home, tags: ['all'] },
  { id: '1', path: '/chapter1', title: 'خلاصه مدیریتی', subtitle: 'Executive Summary', icon: Target, tags: ['business', 'market'] },
  { id: '2', path: '/company', title: 'معرفی استارتاپ', subtitle: 'Company Overview', icon: Building2, tags: ['business'] },
  { id: '3', path: '/problem', title: 'مسئله و فرصت بازار', subtitle: 'Problem & Market Need', icon: TrendingUp, tags: ['market'] },
  { id: '4', path: '/solution', title: 'راهکار پیشنهادی', subtitle: 'Proposed Solution', icon: Cpu, tags: ['product'] },
  { id: '5', path: '/products', title: 'محصولات و خدمات', subtitle: 'Products & Services', icon: Workflow, tags: ['product'] },
  { id: '6', path: '/tech-architecture', title: 'معماری زیرساخت', subtitle: 'Tech Architecture', icon: Server, tags: ['tech'] },
  { id: '7', path: '/ai-architecture', title: 'معماری هوش مصنوعی', subtitle: 'AI Architecture', icon: Brain, tags: ['tech', 'ai'] },
  { id: '8', path: '/business-model', title: 'مدل درآمدی و تجاری', subtitle: 'Business & Revenue', icon: Database, tags: ['business'] },
  { id: '9', path: '/go-to-market', title: 'برنامه بازاریابی', subtitle: 'Go-to-Market', icon: BrainCircuit, tags: ['market'] },
  { id: '10', path: '/team', title: 'تیم و ساختار سازمانی', subtitle: 'Team Structure', icon: Users, tags: ['business'] },
  { id: '11', path: '/investment', title: 'نقشه راه و سرمایه‌گذاری', subtitle: 'Roadmap & Investment', icon: TrendingUp, tags: ['business'] },
  { id: '12', path: '/agent-orchestration', title: 'ارکستراسیون عامل‌ها', subtitle: 'Agent Orchestration', icon: Settings, tags: ['tech', 'ai'] },
  { id: '13', path: '/knowledge-platform', title: 'سکوی دانش سلامت', subtitle: 'Knowledge Platform', icon: BookOpen, tags: ['product', 'tech'] },
  { id: '14', path: '/world-model', title: 'شبیه‌سازی جهان سلامت', subtitle: 'World Model & Simulation', icon: Globe2, tags: ['ai'] },
  { id: '15', path: '/security', title: 'امنیت و حریم خصوصی', subtitle: 'Security & Privacy', icon: Shield, tags: ['legal', 'tech'] },
  { id: '16', path: '/compliance', title: 'قوانین و انطباق', subtitle: 'Regulatory Compliance', icon: Scale, tags: ['legal'] },
  { id: '17', path: '/integration', title: 'یکپارچگی سیستم‌ها', subtitle: 'Integration', icon: Link, tags: ['tech'] },
  { id: '18', path: '/ux', title: 'رابط‌های شناختی', subtitle: 'UX & Interfaces', icon: Smartphone, tags: ['product'] },
  { id: '19', path: '/economics', title: 'اقتصاد پلتفرم', subtitle: 'Platform Economics', icon: DollarSign, tags: ['business'] },
  { id: '20', path: '/marketplace', title: 'بازار نرم‌افزارها', subtitle: 'App Store & Marketplace', icon: Store, tags: ['product', 'market'] },
  { id: '21', path: '/ai-governance', title: 'حاکمیت هوش مصنوعی', subtitle: 'AI Governance', icon: ShieldAlert, tags: ['ai', 'legal'] },
  { id: '22', path: '/operations', title: 'عملیات و AgentOps', subtitle: 'Operations & DevOps', icon: Activity, tags: ['business', 'tech'] },
  { id: '23', path: '/global-expansion', title: 'استراتژی توسعه جهانی', subtitle: 'Global Expansion', icon: Globe, tags: ['market', 'business'] },
  { id: '24', path: '/financials', title: 'پیش‌بینی‌های مالی', subtitle: 'Financial Projections', icon: PieChart, tags: ['business'] },
  { id: '25', path: '/product-catalog', title: 'کاتالوگ جامع محصولات', subtitle: 'Product Catalog', icon: Target, tags: ['product'] },
  { id: '26', path: '/workflows', title: 'سناریوها و جریان‌های کاری', subtitle: 'Workflows & Scenarios', icon: Target, tags: ['product'] },
  { id: '27', path: '/design-system', title: 'سیستم دیزاین و UX', subtitle: 'Design System & UI', icon: Target, tags: ['tech', 'product'] },
  { id: '28', path: '/decision-engines', title: 'موتورهای تصمیم‌ساز', subtitle: 'Decision Engines', icon: Target, tags: ['ai', 'tech'] },
  { id: '29', path: '/deployment-sla', title: 'استقرار، امنیت و SLA', subtitle: 'Deployment & SLA', icon: Target, tags: ['tech', 'legal'] },
  { id: '30', path: '/enterprise-knowledge', title: 'سیستم دانش سازمانی', subtitle: 'Enterprise Knowledge', icon: Target, tags: ['tech', 'business'] },
  { id: '31', path: '/smart-health-record', title: 'پرونده سلامت هوشمند', subtitle: 'Smart Health Record', icon: Target, tags: ['product'] },
  { id: '32', path: '/ai-doctor', title: 'پزشک هوشمند', subtitle: 'AI Doctor', icon: Target, tags: ['product', 'ai'] },
  { id: '33', path: '/ai-orchestration-platform', title: 'پلتفرم هوش مصنوعی مرکزی', subtitle: 'AI Orchestration Platform', icon: Target, tags: ['tech', 'ai'] },
  { id: '34', path: '/agent-platform', title: 'سیستم‌عامل ایجنت‌های پزشکی', subtitle: 'Agent Platform', icon: Target, tags: ['tech', 'ai'] },
  { id: '35', path: '/healthcare-knowledge-graph', title: 'گراف دانش سلامت', subtitle: 'Healthcare Knowledge Graph', icon: Target, tags: ['tech', 'ai'] },
  { id: '36', path: '/digital-human-platform', title: 'همزاد دیجیتال سلامت', subtitle: 'Digital Human Platform', icon: Target, tags: ['product', 'ai'] },
  { id: '37', path: '/healthcare-super-app', title: 'سوپر اپلیکیشن سلامت', subtitle: 'Healthcare Super App', icon: Target, tags: ['product'] },
  { id: '38', path: '/healthcare-enterprise-platform', title: 'پلتفرم سازمانی سلامت', subtitle: 'Healthcare Enterprise Platform', icon: Target, tags: ['product', 'business'] },
  { id: '39', path: '/healthcare-data-ai-platform', title: 'پلتفرم داده و هوش مصنوعی', subtitle: 'Healthcare Data & AI Platform', icon: Target, tags: ['tech', 'ai'] },
  { id: '40', path: '/healthcare-ecosystem-strategy', title: 'استراتژی اکوسیستم سلامت', subtitle: 'Healthcare Ecosystem Strategy', icon: Target, tags: ['market'] },
  { id: '41', path: '/platform-architecture', title: 'معماری کلان پلتفرم', subtitle: 'Platform Architecture', icon: Target, tags: ['tech'] },
  { id: '42', path: '/engineering-platform', title: 'معماری مهندسی و توسعه', subtitle: 'Engineering Platform', icon: Target, tags: ['tech'] },
  { id: '43', path: '/haios', title: 'سیستم‌عامل هوش مصنوعی سلامت', subtitle: 'HAIOS', icon: Target, tags: ['tech', 'ai'] },
  { id: '44', path: '/business-operating-system', title: 'سیستم‌عامل کسب‌وکار', subtitle: 'Business Operating System', icon: Target, tags: ['business', 'tech'] },
  { id: '45', path: '/healthcare-ai-constitution', title: 'قانون اساسی هوش مصنوعی', subtitle: 'Healthcare AI Constitution', icon: Target, tags: ['ai', 'legal'] },
  { id: '46', path: '/healthcare-reference-architecture', title: 'معماری مرجع سلامت', subtitle: 'Healthcare Reference Architecture', icon: Target, tags: ['tech'] },
  { id: '47', path: '/ai-psychologist', title: 'روانشناس هوشمند', subtitle: 'AI Psychologist', icon: Target, tags: ['product', 'ai'] },
  { id: '48', path: '/ai-nutrition-fitness', title: 'مربی سلامت و تغذیه', subtitle: 'AI Nutrition & Fitness Coach', icon: Target, tags: ['product', 'ai'] },
  { id: '49', path: '/smart-pharmacy-lab', title: 'داروخانه و آزمایشگاه', subtitle: 'Smart Pharmacy & Laboratory', icon: Target, tags: ['product'] },
  { id: '50', path: '/smart-insurance-prescription', title: 'بیمه هوشمند و نسخه', subtitle: 'Smart Insurance & e-Prescription', icon: Target, tags: ['product', 'business'] },
  { id: '51', path: '/personalization-monitoring', title: 'موتور شخصی‌سازی و پایش', subtitle: 'Personalization & Monitoring', icon: Target, tags: ['product', 'ai'] },
  { id: '52', path: '/enterprise-api-integration', title: 'مستندات API سازمانی', subtitle: 'Enterprise API & Integration', icon: Target, tags: ['tech'] },
  { id: '53', path: '/deployment-pricing', title: 'مدل‌های استقرار و قیمت‌گذاری', subtitle: 'Deployment Models & Pricing', icon: Target, tags: ['business', 'market'] },
  { id: '54', path: '/competitive-analysis', title: 'تحلیل رقبا', subtitle: 'Competitive Analysis', icon: PieChart, tags: ['market'] },
  { id: '55', path: '/swot', title: 'تحلیل SWOT', subtitle: 'SWOT Analysis', icon: Target, tags: ['business', 'market'] },
  { id: '56', path: '/personas', title: 'پرسونای مخاطبان', subtitle: 'User Personas', icon: Users, tags: ['product', 'market'] },
  { id: '57', path: '/roadmap', title: 'نقشه راه محصول', subtitle: 'Product Roadmap', icon: TrendingUp, tags: ['business', 'product'] },
  { id: '58', path: '/system-architecture', title: 'معماری سیستم و طرح داده', subtitle: 'System Architecture & ERD', icon: Server, tags: ['tech'] },
  { id: '59', path: '/api-docs', title: 'مستندات API و یکپارچه‌سازی', subtitle: 'API & Integration Docs', icon: Link, tags: ['tech'] },
  { id: '60', path: '/compliance-security', title: 'امنیت و انطباق استانداردها', subtitle: 'Compliance & Security', icon: Shield, tags: ['legal', 'tech'] },
  { id: '61', path: '/financial-statements', title: 'صورت‌های مالی و سهم‌داری', subtitle: 'Financials & Cap Table', icon: DollarSign, tags: ['business'] },
  { id: '62', path: '/legal-framework', title: 'مجوزها و قرارداد نمونه', subtitle: 'Legal & Contracts', icon: Scale, tags: ['legal'] },
  { id: '63', path: '/operational-sops', title: 'روش‌های اجرایی و تداوم کسب‌وکار', subtitle: 'Operations & BCP', icon: Activity, tags: ['business'] },
  { id: '64', path: '/prd-prototype', title: 'سند محصول و وایرفریم‌ها', subtitle: 'PRD & Prototype', icon: Smartphone, tags: ['product'] },
  { id: '65', path: '/project-master-record', title: 'شناسنامه جامع پروژه', subtitle: 'Project Master Record', icon: Briefcase, tags: ['knowledge_base'] },
  { id: '66', path: '/glossary', title: 'واژه‌نامه مرکزی پروژه', subtitle: 'Glossary', icon: BookMarked, tags: ['knowledge_base'] },
  { id: '67', path: '/product-capability-registry', title: 'رجیستری محصولات و قابلیت‌ها', subtitle: 'Product & Capability Registry', icon: ClipboardList, tags: ['knowledge_base'] },
  { id: '68', path: '/requirements-repository', title: 'مخزن نیازمندی‌ها', subtitle: 'Requirements Repository', icon: CheckCircle, tags: ['knowledge_base'] },
  { id: '69', path: '/project-status', title: 'وضعیت واقعی پروژه', subtitle: 'Project Status', icon: Activity, tags: ['knowledge_base'] },
  { id: '70', path: '/clinical-safety', title: 'ایمنی بالینی و ریسک پزشکی', subtitle: 'Clinical Safety Case', icon: Stethoscope, tags: ['knowledge_base'] },
  { id: '71', path: '/decision-log', title: 'دفتر تصمیمات پروژه', subtitle: 'Decision Log', icon: HelpCircle, tags: ['knowledge_base'] },
  { id: '72', path: '/assumption-register', title: 'ثبت فرضیات', subtitle: 'Assumption Register', icon: FileText, tags: ['knowledge_base'] },
  { id: '73', path: '/gap-register', title: 'شکاف‌ها و ابهامات', subtitle: 'Gap Register', icon: FileSearch, tags: ['knowledge_base'] },
  { id: '74', path: '/risk-register', title: 'ثبت جامع ریسک‌ها', subtitle: 'Risk Register', icon: ShieldAlert, tags: ['knowledge_base'] },
  { id: '75', path: '/evidence-research', title: 'مخزن تحقیقات و شواهد', subtitle: 'Evidence & Research Library', icon: BookOpen, tags: ['knowledge_base'] },
  { id: '76', path: '/data-dictionary', title: 'فرهنگ داده اجرایی', subtitle: 'Data Dictionary', icon: Database, tags: ['knowledge_base'] },
  { id: '77', path: '/stakeholders-roles', title: 'ماتریس نقش‌ها و ذی‌نفعان', subtitle: 'Stakeholders & Roles', icon: UserCheck, tags: ['knowledge_base'] },
  { id: '78', path: '/integration-traceability', title: 'نقشه اتصال و ردیابی', subtitle: 'Integration & Traceability', icon: Network, tags: ['knowledge_base'] },
  { id: 'export', path: '#', title: 'دانلود مستند یکپارچه', subtitle: 'Export HTML', icon: Download, tags: ['all'] },
];

export const getTagLabel = (tag) => {
  const map = {
    business: 'کسب‌وکار و مالی',
    tech: 'فناوری و زیرساخت',
    product: 'محصول و خدمات',
    ai: 'هوش مصنوعی',
    market: 'بازار و استراتژی',
    legal: 'حقوقی و امنیت',
    knowledge_base: 'مرکز اطلاعات پروژه',
    all: ''
  };
  return map[tag] || '';
};
